# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    backendServiceArm: 'msdn(4136a65d-4704-467a-85b6-12d37a419e4b)'
    backendAzureRmResourceGroupName: 'terraform'
    backendAzureRmStorageAccountName: 'tfstatepardus'
    backendAzureRmContainerName: 'tf'
    backendAzureRmKey: 'terraform.tfstate'